### ISSUE TITLE
Polkadot API init fails with the new node

### ISSUE THREAD

**Issue by lumir-mrkva** [galacticcouncil/HydraDX-claims#17]
```
RPC-CORE: getMetadata(at?: BlockHash): Metadata:: createType(Metadata):: decodeU8a: failed at 0x0ed906000c1c7370… on metadata:: Unable to create Enum via index 14, in V0, V1, V2, V3, V4, V5, V6, V7, V8, V9, V10, V11, V12, V13
API/INIT: Error: FATAL: Unable to initialize the API: createType(Metadata):: decodeU8a: failed at 0x0ed906000c1c7370… on metadata:: Unable to create Enum via index 14, in V0, V1, V2, V3, V4, V5, V6, V7, V8, V9, V10, V11, V12, V13
    at $m.value (Init.js:70:25)
API/INIT: Error: createType(Metadata):: decodeU8a: failed at 0x0ed906000c1c7370… on metadata:: Unable to create Enum via index 14, in V0, V1, V2, V3, V4, V5, V6, V7, V8, V9, V10, V11, V12, V13
    at qc (createType.js:46:11)
    at Eb._formatOutput (index.js:357:12)
    at a (index.js:223:42)
```

polkadot js api probably has to be upgraded to support new node as the type initiation failed

**Comment by paulinechi** [comment]
Hi I'm having the same issue with "@polkadot/api": "^9.8.2", how did you fix it?
